cc_library(
    name = "cppitertools",
    hdrs = [
        "accumulate.hpp",
        "chain.hpp",
        "chunked.hpp",
        "combinations.hpp",
        "combinations_with_replacement.hpp",
        "compress.hpp",
        "count.hpp",
        "cycle.hpp",
        "dropwhile.hpp",
        "enumerate.hpp",
        "filter.hpp",
        "filterfalse.hpp",
        "groupby.hpp",
        "imap.hpp",
        "itertools.hpp",
        "permutations.hpp",
        "powerset.hpp",
        "product.hpp",
        "range.hpp",
        "repeat.hpp",
        "reversed.hpp",
        "slice.hpp",
        "sliding_window.hpp",
        "sorted.hpp",
        "starmap.hpp",
        "takewhile.hpp",
        "unique_everseen.hpp",
        "unique_justseen.hpp",
        "zip.hpp",
        "zip_longest.hpp",
    ],
    srcs = [
        "internal/iter_tuples.hpp",
        "internal/iterator_wrapper.hpp",
        "internal/iteratoriterator.hpp",
        "internal/iterbase.hpp",
    ],
    visibility = ["//visibility:public"],
)
