import os

env = Environment(
    ENV = {'PATH' : os.environ['PATH']},
    CXX='c++',
    CXXFLAGS= ['-g', '-Wall', '-Wextra',
               '-pedantic', '-std=c++14',
                '-fdiagnostics-color=always',
               '-I/usr/local/include'],
    CPPPATH='..',
    LINKFLAGS='-L/usr/local/lib')

# allows highighting to print to terminal from compiler output
env['ENV']['TERM'] = os.environ['TERM']

progs = Split('''
              accumulate
              cycle 
              enumerate 
              range 
              zip 
              slice 
              reversed 
              filter 
              repeat 
              takewhile 
              dropwhile 
              zip_longest 
              product 
              permutations 
              compress 
              combinations_with_replacement 
              combinations 
              powerset
              sliding_window
              imap
              starmap
              count
              filterfalse
              grouper
              chain
              chainfromiterable
              groupby
              sorted
              unique_justseen
              unique_everseen
              command_chains
              ''')


for p in progs:
    env.Program('test{0}.cpp'.format(p))
